/**
 * Browser ASS/SSA subtitle renderer powered by the pure-Rust rassa engine.
 *
 * High-level video overlay rendering, WASM initialization, font registration,
 * GPU composition, and worker/offscreen helpers.
 *
 * @module
 */

/** High-level video/canvas ASS renderer with RVFC sync and GPU fallback. */
export { AssRenderer } from './wrapper'

/** Alias of {@link AssRenderer} for AkariSub-compatible integrations. */
export { AkariSub } from './wrapper'

/** Default export of {@link AssRenderer}. */
export { default } from './wrapper'

export {
  AssParser,
  createAssRenderer,
  detectSubtitleFormat,
  renderFrameData,
  toBlob,
  toCanvas,
  toImageBitmap,
  initWasm,
  isWasmInitialized,
  getWasm,
  getWasmUrl,
  registerFont,
  registerAvailableFonts,
  registerFontBytes,
  registerFontData,
  setFallbackFonts,
  DEFAULT_AVAILABLE_FONTS,
  DEFAULT_FALLBACK_FONTS,
  clearRegisteredFonts,
  listRegisteredFonts,
  resolveFont,
  openAss,
  colorMatrixConversionMap,
  computeCanvasSize,
  dropBlur,
  fixAlpha,
  fixPlayRes,
  getAlphaBug,
  getBitmapBug,
  getColorSpaceFilterUrl,
  getVideoPosition,
  libassYCbCrMap,
  parseAss,
  runFeatureTests,
  testImageBugs,
  webYCbCrMap,
  WebGPURenderer,
  isWebGPUSupported,
  WebGL2Renderer,
  isWebGL2Supported,
  composeAssFrameCpu,
  putCompositionOnCanvas,
  AssRendererWorkerClient,
  createAssRendererWorkerClient,
  createEncryptedSubtitleContent,
  decryptSubtitleContent,
  importAesGcmKey,
  MAX_FONT_BYTES,
  MAX_FRAME_PREFETCH,
  MAX_RENDER_IMAGES,
  MAX_RENDER_PIXELS,
  compensatedMediaTime,
  compositorScheduleLeadMs,
  estimateRefreshIntervalMs,
  frameIndexAtOrAfter,
  isStalePresentation,
  nearestFrameIndex,
  normalizeFrameTimeline,
  presentationLeadSeconds,
  predictFrameDisplayTimeMs,
  presentedFrameIndex,
  resolvePresentationMediaTime,
  secondsToAssMs,
  selectRenderMediaTime,
  snapToFrameTimeline,
  snapToSubtitleTimeline,
  subtitleTimeForFrame,
  updateTimingCompensation
} from './wrapper'

export type {
  AssCueBounds,
  AssFrameRenderOptions,
  AssMetadata,
  AssRenderedFrameData,
  AssSubtitleData,
  AssSubtitleFormatName,
  ASSEvent,
  ASSEventCallback,
  ASSStyle,
  ASSStyleCallback,
  AkariSubOptions,
  EncryptedSubtitleContent,
  FrameTimeline,
  OpenedAssSubtitles,
  PerformanceStats,
  PerformanceStatsCallback,
  RawASSImage,
  RenderImage,
  RenderMessage,
  RenderTimes,
  ResetStatsCallback,
  SubtitleColorSpace,
  VideoAssSubtitleOptions,
  VideoFrameCallbackMetadata,
  WebYCbCrColorSpace,
  RwssFrameCropMode,
  RwssPlaneData,
  RwssRendererBackend,
  RwssRendererEvent,
  RwssRendererStatsSnapshot,
  RwssFontSource,
  RwssFontLoadOptions,
  RwssAvailableFontLoadOptions,
  RwssRegisteredFont,
  RwssResolvedFont,
  RwssImageCompositionResult,
  AssRendererWorkerClientOptions,
  SerializableWorkerOptions,
  RwssWorkerRequest,
  RwssWorkerResponse,
  RwssRawAesKey,
  WorkerInitMessage,
  WorkerInboundMessage,
  WorkerOutboundMessage
} from './wrapper'
